package com.syzc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollection<M extends BaseCollection<M>> extends Model<M> implements IBean {

	public void setCId(java.lang.Integer cId) {
		set("c_id", cId);
	}

	public java.lang.Integer getCId() {
		return get("c_id");
	}

	public void setCKId(java.lang.Integer cKId) {
		set("c_k_id", cKId);
	}

	public java.lang.Integer getCKId() {
		return get("c_k_id");
	}

	public void setCUId(java.lang.Integer cUId) {
		set("c_u_id", cUId);
	}

	public java.lang.Integer getCUId() {
		return get("c_u_id");
	}

	public void setCAddtime(java.util.Date cAddtime) {
		set("c_addtime", cAddtime);
	}

	public java.util.Date getCAddtime() {
		return get("c_addtime");
	}

	public void setCUpdatetime(java.util.Date cUpdatetime) {
		set("c_updatetime", cUpdatetime);
	}

	public java.util.Date getCUpdatetime() {
		return get("c_updatetime");
	}

}
