package com.syzc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFirm<M extends BaseFirm<M>> extends Model<M> implements IBean {

	public void setFId(java.lang.Integer fId) {
		set("f_id", fId);
	}

	public java.lang.Integer getFId() {
		return get("f_id");
	}

	public void setFName(java.lang.String fName) {
		set("f_name", fName);
	}

	public java.lang.String getFName() {
		return get("f_name");
	}

	public void setFAddress(java.lang.String fAddress) {
		set("f_address", fAddress);
	}

	public java.lang.String getFAddress() {
		return get("f_address");
	}

	public void setFMail(java.lang.String fMail) {
		set("f_mail", fMail);
	}

	public java.lang.String getFMail() {
		return get("f_mail");
	}

	public void setFState(java.lang.Integer fState) {
		set("f_state", fState);
	}

	public java.lang.Integer getFState() {
		return get("f_state");
	}

	public void setFCorporation(java.lang.String fCorporation) {
		set("f_corporation", fCorporation);
	}

	public java.lang.String getFCorporation() {
		return get("f_corporation");
	}

	public void setFCode(java.lang.String fCode) {
		set("f_code", fCode);
	}

	public java.lang.String getFCode() {
		return get("f_code");
	}

	public void setFPhone(java.lang.String fPhone) {
		set("f_phone", fPhone);
	}

	public java.lang.String getFPhone() {
		return get("f_phone");
	}

	public void setFDesc(java.lang.String fDesc) {
		set("f_desc", fDesc);
	}

	public java.lang.String getFDesc() {
		return get("f_desc");
	}

	public void setFPassword(java.lang.String fPassword) {
		set("f_password", fPassword);
	}

	public java.lang.String getFPassword() {
		return get("f_password");
	}

	public void setFAddtime(java.util.Date fAddtime) {
		set("f_addtime", fAddtime);
	}

	public java.util.Date getFAddtime() {
		return get("f_addtime");
	}

	public void setFUpdatetime(java.util.Date fUpdatetime) {
		set("f_updatetime", fUpdatetime);
	}

	public java.util.Date getFUpdatetime() {
		return get("f_updatetime");
	}

}
