package com.syzc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKnowledge<M extends BaseKnowledge<M>> extends Model<M> implements IBean {

	public void setKId(java.lang.Integer kId) {
		set("k_id", kId);
	}

	public java.lang.Integer getKId() {
		return get("k_id");
	}

	public void setKFId(java.lang.Integer kFId) {
		set("k_f_id", kFId);
	}

	public java.lang.Integer getKFId() {
		return get("k_f_id");
	}

	public void setKUId(java.lang.Integer kUId) {
		set("k_u_id", kUId);
	}

	public java.lang.Integer getKUId() {
		return get("k_u_id");
	}

	public void setKName(java.lang.String kName) {
		set("k_name", kName);
	}

	public java.lang.String getKName() {
		return get("k_name");
	}

	public void setKState(java.lang.Integer kState) {
		set("k_state", kState);
	}

	public java.lang.Integer getKState() {
		return get("k_state");
	}

	public void setKCollect(java.lang.Long kCollect) {
		set("k_collect", kCollect);
	}

	public java.lang.Long getKCollect() {
		return get("k_collect");
	}

	public void setKClick(java.lang.Long kClick) {
		set("k_click", kClick);
	}

	public java.lang.Long getKClick() {
		return get("k_click");
	}

	public void setKDownload(java.lang.Long kDownload) {
		set("k_download", kDownload);
	}

	public java.lang.Long getKDownload() {
		return get("k_download");
	}

	public void setKPath(java.lang.String kPath) {
		set("k_path", kPath);
	}

	public java.lang.String getKPath() {
		return get("k_path");
	}

	public void setKNewpath(java.lang.String kNewpath) {
		set("k_newPath", kNewpath);
	}

	public java.lang.String getKNewpath() {
		return get("k_newPath");
	}

	public void setKAddtime(java.util.Date kAddtime) {
		set("k_addtime", kAddtime);
	}

	public java.util.Date getKAddtime() {
		return get("k_addtime");
	}

	public void setKUpdatetime(java.util.Date kUpdatetime) {
		set("k_updatetime", kUpdatetime);
	}

	public java.util.Date getKUpdatetime() {
		return get("k_updatetime");
	}

}
