package com.syzc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUId(java.lang.Integer uId) {
		set("u_id", uId);
	}

	public java.lang.Integer getUId() {
		return get("u_id");
	}

	public void setUPwd(java.lang.String uPwd) {
		set("u_pwd", uPwd);
	}

	public java.lang.String getUPwd() {
		return get("u_pwd");
	}

	public void setUName(java.lang.String uName) {
		set("u_name", uName);
	}

	public java.lang.String getUName() {
		return get("u_name");
	}

	public void setUGender(java.lang.String uGender) {
		set("u_gender", uGender);
	}

	public java.lang.String getUGender() {
		return get("u_gender");
	}

	public void setUPhone(java.lang.String uPhone) {
		set("u_phone", uPhone);
	}

	public java.lang.String getUPhone() {
		return get("u_phone");
	}

	public void setUAge(java.lang.Integer uAge) {
		set("u_age", uAge);
	}

	public java.lang.Integer getUAge() {
		return get("u_age");
	}

	public void setUEmail(java.lang.String uEmail) {
		set("u_email", uEmail);
	}

	public java.lang.String getUEmail() {
		return get("u_email");
	}

	public void setUFirm(java.lang.Integer uFirm) {
		set("u_firm", uFirm);
	}

	public java.lang.Integer getUFirm() {
		return get("u_firm");
	}

	public void setURole(java.lang.Integer uRole) {
		set("u_role", uRole);
	}

	public java.lang.Integer getURole() {
		return get("u_role");
	}

	public void setUAddtime(java.util.Date uAddtime) {
		set("u_addtime", uAddtime);
	}

	public java.util.Date getUAddtime() {
		return get("u_addtime");
	}

	public void setUUpdatetime(java.util.Date uUpdatetime) {
		set("u_updatetime", uUpdatetime);
	}

	public java.util.Date getUUpdatetime() {
		return get("u_updatetime");
	}

}
