package com.syzc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLabel<M extends BaseLabel<M>> extends Model<M> implements IBean {

	public void setLId(java.lang.Integer lId) {
		set("l_id", lId);
	}

	public java.lang.Integer getLId() {
		return get("l_id");
	}

	public void setLFId(java.lang.Integer lFId) {
		set("l_f_id", lFId);
	}

	public java.lang.Integer getLFId() {
		return get("l_f_id");
	}

	public void setLName(java.lang.String lName) {
		set("l_name", lName);
	}

	public java.lang.String getLName() {
		return get("l_name");
	}

	public void setLAddtime(java.util.Date lAddtime) {
		set("l_addtime", lAddtime);
	}

	public java.util.Date getLAddtime() {
		return get("l_addtime");
	}

	public void setLUpdatetime(java.util.Date lUpdatetime) {
		set("l_updatetime", lUpdatetime);
	}

	public java.util.Date getLUpdatetime() {
		return get("l_updatetime");
	}

}
