package com.syzc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseType<M extends BaseType<M>> extends Model<M> implements IBean {

	public void setTId(java.lang.Integer tId) {
		set("t_id", tId);
	}

	public java.lang.Integer getTId() {
		return get("t_id");
	}

	public void setTLId(java.lang.Integer tLId) {
		set("t_l_id", tLId);
	}

	public java.lang.Integer getTLId() {
		return get("t_l_id");
	}

	public void setTKId(java.lang.Integer tKId) {
		set("t_k_id", tKId);
	}

	public java.lang.Integer getTKId() {
		return get("t_k_id");
	}

	public void setTAddtime(java.util.Date tAddtime) {
		set("t_addtime", tAddtime);
	}

	public java.util.Date getTAddtime() {
		return get("t_addtime");
	}

	public void setTUpdatetime(java.util.Date tUpdatetime) {
		set("t_updatetime", tUpdatetime);
	}

	public java.util.Date getTUpdatetime() {
		return get("t_updatetime");
	}

}
