package com.syzc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePath<M extends BasePath<M>> extends Model<M> implements IBean {

	public void setPId(java.lang.Integer pId) {
		set("p_id", pId);
	}

	public java.lang.Integer getPId() {
		return get("p_id");
	}

	public void setPKId(java.lang.Integer pKId) {
		set("p_k_id", pKId);
	}

	public java.lang.Integer getPKId() {
		return get("p_k_id");
	}

	public void setPPath(java.lang.String pPath) {
		set("p_path", pPath);
	}

	public java.lang.String getPPath() {
		return get("p_path");
	}

	public void setPAddtime(java.util.Date pAddtime) {
		set("p_addtime", pAddtime);
	}

	public java.util.Date getPAddtime() {
		return get("p_addtime");
	}

	public void setPUpdatetime(java.util.Date pUpdatetime) {
		set("p_updatetime", pUpdatetime);
	}

	public java.util.Date getPUpdatetime() {
		return get("p_updatetime");
	}

}
