package com.syzc.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("administrator", "a_id", Administrator.class);
		arp.addMapping("collection", "c_id", Collection.class);
		arp.addMapping("comment", "com_id", Comment.class);
		arp.addMapping("firm", "f_id", Firm.class);
		arp.addMapping("knowledge", "k_id", Knowledge.class);
		arp.addMapping("label", "l_id", Label.class);
		arp.addMapping("path", "p_id", Path.class);
		arp.addMapping("type", "t_id", Type.class);
		arp.addMapping("user", "u_id", User.class);
	}
}

