package com.syzc.common.model;

import com.syzc.common.model.base.BaseAdministrator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Administrator extends BaseAdministrator<Administrator> {
	public static final Administrator dao = new Administrator().dao();
}
