package com.syzc.common.model;

import com.syzc.common.model.base.BaseFirm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Firm extends BaseFirm<Firm> {
	public static final Firm dao = new Firm().dao();
}
