package com.syzc.common.model;

import com.syzc.common.model.base.BaseKnowledge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Knowledge extends BaseKnowledge<Knowledge> {
	public static final Knowledge dao = new Knowledge().dao();
}
