package com.syzc.common.model;

import com.syzc.common.model.base.BasePath;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Path extends BasePath<Path> {
	public static final Path dao = new Path().dao();
}
